{% set python_min = "3.10" %}
{% set name = "patool" %}
{% set version = "4.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/patool-{{ version }}.tar.gz
  sha256: 41f7ee21be337a5baf07b2cb4796e9d94397ab741d2379c622f98fc001099802

build:
  entry_points:
    - patool = patoolib.cli:main_cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - setuptools_reproducible
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - patoolib
  commands:
    - pip check
    - patool --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: http://wummel.github.io/patool/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: patool is a portable command line archive file manager
  dev_url: https://github.com/wummel/patool

extra:
  recipe-maintainers:
    - notestaff
    - ocefpaf
