{% set name = "patool" %}
{% set version = "2.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/patool-{{ version }}.tar.gz
  sha256: d55d82694038aae18bc34be25ef29d042c244f93a03a4f66c8b4d218f927e7cb

build:
  entry_points:
    - patool = patoolib.cli:main_cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.10
    - setuptools
    - pip
  run:
    - python >=3.10

test:
  imports:
    - patoolib
  commands:
    - pip check
    - patool --help
  requires:
    - pip

about:
  home: http://wummel.github.io/patool/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: patool is a portable command line archive file manager
  dev_url: https://github.com/wummel/patool

extra:
  recipe-maintainers:
    - notestaff
    - ocefpaf
