{% set name = "patool" %}
{% set version = "1.14.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/patool-{{ version }}.tar.gz
  sha256: 9a6e41576581a15784e58a83b43ba54fee89884c10446224c948d23fce9e666b

build:
  entry_points:
    - patool = patoolib.cli:main_cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools
    - pip
  run:
    - python >=3.9

test:
  imports:
    - patoolib
  commands:
    - pip check
    - patool --help
  requires:
    - pip

about:
  home: http://wummel.github.io/patool/
  license: GPL-3.0
  license_family: GPL
  license_file: COPYING
  summary: 'portable archive file manager'
  dev_url: https://github.com/wummel/patool

extra:
  recipe-maintainers:
    - notestaff
    - ocefpaf
