schema_version: 1

context:
  python_min: "3.12"
  version: "4.1.0"

package:
  name: patool
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/p/patool/patool-${{ version }}.tar.gz
  sha256: 54c669b2af0f5e46d59a53f02ca4f83d53b3a7a25d50e97778582da7cea65daf

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - patool = patoolib.cli:main_cli

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools_reproducible >=0.1
    - pip
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - patoolib
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - patool --help

about:
  summary: portable archive file manager
  license: GPL-3.0-only
  license_file: COPYING
  homepage: https://github.com/wummel/patool
  repository: https://github.com/wummel/patool

extra:
  recipe-maintainers:
    - notestaff
    - ocefpaf
