schema_version: 1

context:
  version: "4.0.7"

package:
  name: patool
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/p/patool/patool-${{ version }}.tar.gz
  sha256: 08dcb019997f55aa730a873185aeddbb397e2be757157769721942784cb4a97f

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - patool = patoolib.cli:main_cli

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools_reproducible >=0.1
    - pip
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - patoolib
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - patool --help

about:
  summary: portable archive file manager
  license: GPL-3.0-only
  license_file: COPYING
  homepage: https://github.com/wummel/patool
  repository: https://github.com/wummel/patool

extra:
  recipe-maintainers:
    - notestaff
    - ocefpaf
